os: linux
#dist: bionic
#language: python
# python:
#   - "3.7"
#   - "3.8"
#   - "3.8-dev"
#   - "pypy"
#   - "pypy3"

branches:
  only:
  - master

cache:
  pip: true
  directories:
  - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python.version())')"

# env:
#   global:
#     - POPE_DISABLE_PIP=1
#     - PIP_QUIET=0
#     - secure: n/oCBBW4aagLyoIrrGRqgkpofBjXbH3NjwnBL6GO/0z5S3sKg3jX2socN0JYOkVHY7+zk1859HDbZ+Yf+MOiMSiHftDWTYA8afyAAG8BUOYnyLpW+d6HjxFdHty73OK77oHRGoQsX1+WgUCl3eoQreDv3odm02cptygcaHu7UG1twn0ED19X0Opr9HrW0JGq5M1cDRKP/v87RD9c5kfCoHhuzSo94/a9aVxQcTSapnFxJK4sD7FZmc18GYsGETLS7czIWltn6eoBt2sigm5ACLHejE+bQwzge25CK4XtIVsQPZAb3mlDoqfCnD71LYP1FnRM65eWdXIuWGyDwlSQ9v0vNbYLZDzFXiTLj3g6xLsfeDtr8tqexQXD3RWyjWaaxRwaTNn+fRlPF/oreat5xbzekgYecaxWfJ70i4/P/MMXYoFxEQi/ejdFu+rgWUQaZ9Q/tO5Yq5PCYCrKK7wj6x466SeEbVswSMlMFwbLwq3QfwChVI9Di5kQRsdK+i/jHesiXBz4XQ84r/3IKseX+551ry/DctQ4bZFFYB7XQ/mq/v94f3k9jQ1fcvUd8Lu68nD/YsYE5FYmnYJ2lJwznYy3CzBLl0BskaODTKhX3HlSWzxMD18uV6i8n7YmwiPOvqicZrzBZxdCAJavd34wedNRCfaSBiKgtuv8qtVsiGY=
#     - secure: GLixIPLtROGxvW3BynbUJU/rJiFw8R/vleQsmYGEGbc8I9AlSvFa3l0Y4/H0+U4mC4Xzpf9lRfSZM1vp8YiiIgKKv1siSEYS/v52ZquKC9Za/ipqlhok/uGXlT4s4xZptvX3Qqy3V/WBUUrQr7MfzUn55Lc2BPUgCk0wR3MTlXShIHOgtFQMzoIzcFsOU9RLiGqWYSjVjNMy65wfDgAA7LOHkkH/1jajvp7RJVhXlwDt+kZF22e+0u0yKm6nMROUuel1YiCNcWpfiNrArhoLekxijD4WyhNQL3EvhzTiw3WeDHXTCZJ3GlaUcLerjw6MD3vNFW+uR4I23AWwPrsEzrdP6KftYeFRP1t2gkROJMomCUvCq4l7oYNVhOG8I4I5BP0xNIUXYe+zpvSlADibdmNcsR4Mckz1YvyO9tJ238sHK+b79m2raoB764frfhYjigeMYnVRYg/qhy2o2vpb2DeZr3L01soK4JrTz84I8OCIylD5VnGmws8xS9QYbBN4U0Wifr+CyHvq+0wiPFIbLmckDyGe2kR9AlBu3DWyTfQvjXbKswMG3qvsXMgeSSk/vYl4RXa74j0ZOqEJ49JrH6O5aXjJFoBGeCdrGl+rscxUvLWlFpH19DNglCuCJGwTEBwiJnRRhLZM7mYaxCVbtr7r84tLpf4IKwwA7NYYeBs=
language: python
jobs:
  include:
    - name: "Python 3.7"
      python: 3.7
      os: linux
      dist: bionic
    - name: "Python 3.8"
      python: 3.8
      os: linux
      dist: bionic
      before_install:
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip
script: python3 readconf.py || python readconf.py

# - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python_version())')"
#     - "echo $(python --version)"
#   install:
#     - python -m venv .venv
#     - . .venv/bin/activate
#     - python -m pip install --upgrade pip
#     - pip install -q r
#     # - python -m pip install --requirement requirements.txt
#     - pip3 install upgrade pip
#   script:
#     - pytest
#   #after_script:
#     #- | \
#     #  coverage_files=$(ls .artifacts/*coverage.xml || true) \
#     #  if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]] \
#     #  then \
#     #    python -m pip install --upgrade codecov \
#     #    codecov acceptance \
#     #  fi


# notifications:
#   email:
#     recipients:
#       - jflopezfernandez@gmail.com
#     on_success: always
#     on_failure: always
#   webhooks:
#       - https://zeus.ci/gh/jflopezfernandez/readconf/settings/hooks/7546c0b6-98b1-11ea-a359-16d0711c04da
#   pushover:
#       api_key: n/oCBBW4aagLyoIrrGRqgkpofBjXbH3NjwnBL6GO/0z5S3sKg3jX2socN0JYOkVHY7+zk1859HDbZ+Yf+MOiMSiHftDWTYA8afyAAG8BUOYnyLpW+d6HjxFdHty73OK77oHRGoQsX1+WgUCl3eoQreDv3odm02cptygcaHu7UG1twn0ED19X0Opr9HrW0JGq5M1cDRKP/v87RD9c5kfCoHhuzSo94/a9aVxQcTSapnFxJK4sD7FZmc18GYsGETLS7czIWltn6eoBt2sigm5ACLHejE+bQwzge25CK4XtIVsQPZAb3mlDoqfCnD71LYP1FnRM65eWdXIuWGyDwlSQ9v0vNbYLZDzFXiTLj3g6xLsfeDtr8tqexQXD3RWyjWaaxRwaTNn+fRlPF/oreat5xbzekgYecaxWfJ70i4/P/MMXYoFxEQi/ejdFu+rgWUQaZ9Q/tO5Yq5PCYCrKK7wj6x466SeEbVswSMlMFwbLwq3QfwChVI9Di5kQRsdK+i/jHesiXBz4XQ84r/3IKseX+551ry/DctQ4bZFFYB7XQ/mq/v94f3k9jQ1fcvUd8Lu68nD/YsYE5FYmnYJ2lJwznYy3CzBLl0BskaODTKhX3HlSWzxMD18uV6i8n7YmwiPOvqicZrzBZxdCAJavd34wedNRCfaSBiKgtuv8qtVsiGY=
# users:
#   - secure: YBidF620rKxcpB2hsk+67RPjWJknT5np2SdSQOx64oUIFdkBhWCmLIjYIrJPE2cW++iHKKtOY7NQVPGfQcb6AgLdooCq+luMtH2Qq3BWxZkAwGbGLGMfR2OcfM9RtRWwSn7qRfw+myZAo7Qj+tnmPJod80LwSCKrKN0mv0mtPowgMd4NJk6WTGIwrrDLK8PjDtl9YgJFFDJvug7C+ISEjHZ92lfwROv7yBXC4aRAPxHXzgfE7nP+HbT5Kxq4Y1P960R1a50yXlcFta09clIwW93mpJUzplsIOcYFa0peaKRcifqsOOmaKrTVZouvArF21WFtMjzDHXg5Z6JXbp+lucI/nPCbmLHVVc6zdTRooJrDV3oHQD1FHWZ1PB2HIYsLhE47NrAL+wEP+p7DU6wH7lGQL1Xc06fWfB8/qc2GVOGTTvyRqi+bcDOKCsWJT4mkeS0AXP94vSssn+SFZzSIkMNTzJQMFUpX72iNiu+LBSvk7DMfnKe/fgxlcQti98TkrQ9qZTtXa3IsfCC/Fi2N1uJiMFzDXfUSzMjoMyUPM5+DY8GZtsftMQAJk0IslDeUB7f8XCd1kpCykW2tq0lD6ND7Q7Qn3in0UDXNnh3KPt82bwC2SjFFM9z1U+htln6u6/+hI/FSPh67hIO9/ZFU8ul/gSDxLd6Bi1OGREBv1oI=
#   - template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"