dist: bionic
language: python
python: 3.8
branches:
  only:
  - master
cache:
  pip: true
  directories:
  - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python.version())')"
env:
  global:
  - PIP_QUIET=0
  - secure: n/oCBBW4aagLyoIrrGRqgkpofBjXbH3NjwnBL6GO/0z5S3sKg3jX2socN0JYOkVHY7+zk1859HDbZ+Yf+MOiMSiHftDWTYA8afyAAG8BUOYnyLpW+d6HjxFdHty73OK77oHRGoQsX1+WgUCl3eoQreDv3odm02cptygcaHu7UG1twn0ED19X0Opr9HrW0JGq5M1cDRKP/v87RD9c5kfCoHhuzSo94/a9aVxQcTSapnFxJK4sD7FZmc18GYsGETLS7czIWltn6eoBt2sigm5ACLHejE+bQwzge25CK4XtIVsQPZAb3mlDoqfCnD71LYP1FnRM65eWdXIuWGyDwlSQ9v0vNbYLZDzFXiTLj3g6xLsfeDtr8tqexQXD3RWyjWaaxRwaTNn+fRlPF/oreat5xbzekgYecaxWfJ70i4/P/MMXYoFxEQi/ejdFu+rgWUQaZ9Q/tO5Yq5PCYCrKK7wj6x466SeEbVswSMlMFwbLwq3QfwChVI9Di5kQRsdK+i/jHesiXBz4XQ84r/3IKseX+551ry/DctQ4bZFFYB7XQ/mq/v94f3k9jQ1fcvUd8Lu68nD/YsYE5FYmnYJ2lJwznYy3CzBLl0BskaODTKhX3HlSWzxMD18uV6i8n7YmwiPOvqicZrzBZxdCAJavd34wedNRCfaSBiKgtuv8qtVsiGY=
jobs:
  include:
  - language: generic
    name: Start Notifier
    before_install:
    - echo "Starting install..."
install: python -m pip install --upgrade pip
script: "./run-tests.sh"
notifications:
  email:
    recipients:
    - jflopezfernandez@gmail.com
    on_success: always
    on_failure: always
  webhooks:
    urls:
    - https://zeus.ci/hooks/
  pushover:
    users:
    - ukimnzwg9uiv8jrdqk3jbgjkps6w7d
    template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"
